[functions]
  node_bundler = "esbuild"

# Pretty paths: /api/auth and /api/callback
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/callback"
  to = "/.netlify/functions/callback"
  status = 200
